@startuml
start
:Enter login credentials;
:POST /Login.php;
if (Valid credentials?) then (yes)
  :Save session cookie;
  :Redirect to color.html;
  repeat
    switch (Choose action)
    case (Search)
      :Enter search term;
      :POST /SearchColors.php;
      if (Records found?) then (yes)
        :Display color list;
      else (no)
        :Show "No Records Found";
      endif
    case (Add)
      :Enter color name;
      :POST /AddColor.php;
      :Show "Color has been added";
    case (Logout)
      :Clear session cookie;
      :Redirect to index.html;
      stop
    endswitch
  repeat while (Another action?) is (yes)
else (no)
  :Show error message;
endif
stop
@enduml